server:
  port: 3000
  servlet:
    context-path: "/telstra"
spring:
  jpa:
    hibernate.ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H8Dialect
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver